version: '2.1'

services:

  neurosynth:
    image: ghcr.io/adelavega/neurosynth-web:prod
    restart: always
    expose:
      - 8000
    volumes:
      - .:/code
      - /media/data-drive/neurosynth:/data:rw
      - /logs/synth:/logs:rw
    working_dir: /code
    command: /code/scripts/docker_startup.sh
    depends_on:
      - db
      - broker
    environment:
      - VIRTUAL_HOST=deepdream.psy.utexas.edu
      - LETSENCRYPT_HOST=deepdream.psy.utexas.edu

  db:
    restart: always
    image: postgres:10.4
    expose:
      - '5432'
    volumes:
      - /var/www/neurosynth-db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neurosynth
      - POSTGRES_USER=neurosynth

  broker:
    restart: always
    image: redis:latest

  worker:
    build: .
    restart: always
    ports:
      - "8000"
    working_dir: /code
    command: /code/scripts/run_celery.sh
    volumes_from:
      - neurosynth
    depends_on:
      - db
      - broker

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    external:
      name: nginx-proxy

